# -*- coding: utf-8 -*-
"""Chatbot execise.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/16cyrr_-2rHcSKVpxvrJwFZy2kGHmck9J
"""

!pip install langchain --quiet
!pip install openai --quiet
!pip install gradio --quiet

from langchain.chat_models import ChatOpenAI
from langchain.prompts.chat import (
    ChatPromptTemplate,
    SystemMessagePromptTemplate,
    AIMessagePromptTemplate,
    HumanMessagePromptTemplate,
)
from langchain.schema import AIMessage, HumanMessage, SystemMessage

from gradio.components.chatbot import Chatbot
import gradio as gr
import requests


#Riot API KEY --- DON'T STEAL
API_KEY = '' #Use api key here
SUMMERNER_NAME = 'Jessicaclan' #Summoner name used during testing
X = None

def get_ids(summoner_name):
    headers = {'X-Riot-Token': f'{API_KEY}'}
    api_url = f'https://euw1.api.riotgames.com/lol/summoner/v4/summoners/by-name/{summoner_name}'
    x = requests.get(api_url, headers=headers)
    player_id = x.json()['id']
    account_id = x.json()['accountId']
    player_puuid = x.json()['puuid']

    return player_id, account_id, player_puuid

def get_match_ids(player_puuid):
  headers = {'X-Riot-Token': f'{API_KEY}'}
  api_url = f'https://europe.api.riotgames.com/lol/match/v5/matches/by-puuid/{player_puuid}/ids?start=0&count=20&api_key={API_KEY}'
  x = requests.get(api_url, headers=headers)

  return x.json()

def get_match_info(match_id, player_puuid):
  headers = {'X-Riot-Token': f'{API_KEY}'}
  api_url = f'https://europe.api.riotgames.com/lol/match/v5/matches/{match_id}?api_key={API_KEY}'
  x = requests.get(api_url, headers=headers)

  for participant in x.json()["info"]["participants"]:
    if participant["puuid"] == player_puuid:
      return participant

def find_lastest_match(summoner_name):
  global X
  player_id, account_id, player_puuid = get_ids(summoner_name)

  match_ids = get_match_ids(player_puuid)

  for match_id in match_ids:
    X = get_match_info(match_id, player_puuid)
    return True
    break

def aibot(message):

  llm = ChatOpenAI(temperature=0.5,
                 openai_api_key="", #OpenAI api key
                 model = "gpt-3.5-turbo-0613")

  history_langchain_format = []
  history_langchain_format.append(SystemMessage(content = str(X)))
  history_langchain_format.append(HumanMessage(content = message))
  gpt_response = llm(history_langchain_format)
  return gpt_response.content



with gr.Blocks() as demo:
  gr.Markdown("""
      # LOLBot
      Find your account(EUW only) and ask LOLBot about your lastest game
  """)
  with gr.Row():
    with gr.Column():
      summoner_name = gr.Textbox(label="Summoner Name")
      summoner_btn = gr.Button(value="Find Summoner")
      checkbox = gr.Checkbox(label="Ready for message")


  with gr.Row():
    with gr.Column():
      input = gr.Textbox(label="Message")
      submit_btn = gr.Button(value="Submit")

    with gr.Column():
      output = gr.Textbox(label="LoL Bot")

  summoner_btn.click(find_lastest_match, inputs=summoner_name, outputs=checkbox)
  submit_btn.click(aibot, inputs=input, outputs=output)



demo.launch(show_error=True)